- .github/politica_de_branches.md
- .github/politica_de_commit.md
Adiciona políticas de *branches* e *commits* ao repositorio 
Issue [26](https://github.com/fga-gpp-mds/2018.1-Grupo3/issues/26)
> Issue #26 - Criar políticas de repositorios

- docs/templates/sprint_planning.md
- docs/templates/sprint_review.md
Create template for sprint planning and review.
#28
> Templates for sprint planning and review

- docs/templates/sprint_01/sprint_01_planning.md
Create sprint 01 planning document
{mark those that apply}
#31
> [ADD] create sprint 01 planning

- docs/.gitmessage
> [ADD] #69 commit template

- README.md
Adding some description and useful links to README
> [UPDATE] Including README description

- TropicalHazards_BI/settings.py
- boot.sh
- docker-compose.yml
Cria o ambiente de desenvolvimento do back end do projeto(django,postgres).
> Issue 54 backend development enviroment

- docs/templates/sprint_planning.md
- docs/templates/sprint_review.md
- docs/wiki/R1/sprint_00/sprint_00_planning.md
- docs/wiki/R1/sprint_00/sprint_00_review.md
- docs/wiki/R1/sprint_01/sprint_01_planning.md
- docs/wiki/R1/sprint_01/sprint_01_review.md
- docs/wiki/R1/sprint_02/sprint_02_planning.md
Documenta Planning e Review da Sprtin 00 a Sprint 02
> Issue 34 fix sprints docs

- docker-compose.yml
Resolve essa [issue](https://github.com/fga-gpp-mds/2018.1-TropicalHazards-BI/issues/106)
> Issue 106 Chages the database container port

- TropicalHazards_BI/settings.py
- TropicalHazards_BI/urls.py
- manage.py
- requirements.txt
- users/admin.py
- users/apps.py
- users/models.py
- users/serializers.py
- users/tests.py
- users/urls.py
- users/views.py
Devido ao fato das implementações serem relativamente simples nesse PR declaro que não foram necessários criar as branchs relacionadas as seguintes issues: Deletar Usuário (API) issue 89, Editar Usuário (API) issue 91, sendo implementadas na branch issue 88
> Issue 88 criacao usuario api

- docs/wiki/R1/sprint_01/sprint_01_planning.md
- docs/wiki/R1/sprint_01/sprint_01_review.md
- docs/wiki/R1/sprint_02/sprint_02_planning.md
- docs/wiki/R1/sprint_02/sprint_02_review.md
- docs/wiki/R1/sprint_03/sprint_03_planning.md
Criação da documentação de review e retrospectiva da Sprint 02 e planning da Sprint 03, além de melhoria na organização e informações dos arquivos.
> Sprint documentation improvement

- docs/wiki/plano-de-medicao.md
> [DOC] adding measure planning

- .travis.yml
- requirements.txt
Atualiza dependência psycopg e atualiza o Travis file para rodar o pytest.
> Issue 93 fix psycopg

- docs/doc_arquitetura.md
Criado tópico 3 sobre metas e restrições do documento de arquitetura
@IagoCarvalho pode fazer a revisão?
> Issue 83 metas e restricoes doc architecture

- .pyup.yml
- README.md
Adiciona a ferramenta pyup para automatizar a verificação de dependências do python e gerar pull requests de atualizações.
> Issue 124 configuração do pyup

- docs/wiki/doc_visao.md
> Issue 119 refactore doc vision

- docs/wiki/riscos.md
> Issue 127 risk burndown

- docs/wiki/R1/sprint_02/sprint_02_review.md
- docs/wiki/R1/sprint_03/sprint_03_planning.md
- docs/wiki/R1/sprint_03/sprint_03_review.md
- docs/wiki/R1/sprint_04/sprint_04_planning.md
Cria documentação referente a revisão da Sprint 03 e planning da Sprint 04
> Sprint 03 and 04 documentation

- docs/wiki/doc_arquitetura.md
Atualiza tópicos relacionados aos micro serviços do sistema, persistência e visão de dados. Refatora imagens e estruturas quebradas no documento.
> Issue 141 arquitetura dos servicos

- docs/wiki/R1/sprint_02/sprint_02_review.md
- docs/wiki/R1/sprint_03/sprint_03_review.md
- docs/wiki/R1/sprint_04/sprint_04_review.md
- docs/wiki/R1/sprint_05/sprint_05_planning.md
Adiciona Sprint 04 review e Sprint 05 planning, além de corrigir imagens do velocity incorretas das Sprints 02 e 03.
> Sprint 04 and 05 documentation

- README.md
Adiciona links que estavam faltando e atualiza o tópico de instalação.
> issue 187 Atualizar README

- docs/development_docs/doc_arquitetura.md
> [FIX] quick fix on doc_architecture list

- docs/css/shared.css
- docs/index.html
Co-authored-by: Renata Francelino <renata.rfsouza@gmail.com>
> [UPDATE] changes proposed by renata

- docs/css/shared.css
- docs/development_docs/doc_arquitetura.md
- docs/index.html
> hotfix gh-pages

- docs/metodology/sprints/sprint_05/sprint_05_review.md
- docs/metodology/sprints/sprint_06/sprint_06_planning.md
Cria documentação de review da Sprint 05 e planning da Sprint 06
> Sprint 05 and 06 documentation

- TropicalHazards_BI/settings.py
- docker-compose.yml
- requirements.txt
Configura serviço do mongo para ser utilizado pela aplicação django, para utilizar o serviço sugiro recorrer a documentação do [mongoengine](http://docs.mongoengine.org/)
> Configure mongoDB service

- docs/development_docs/doc_arquitetura.md
- Atualização da imagem
- Imagem atualizada para corrigir cardinalidades e adição de relação entre "DASHBOARD" e "USER"
> Update do tópico de Visão de Dados atualizando diagrama ER 

- .gitignore
- package.json
coloquei e configurei o release-it para criação das nossas releases
nao é a solução ideal, mas vai segurar as pontas até sair a solução automatizada baseada em branches
> Adds release-it tool for making releases

- docs/metodology/sprints/sprint_05/sprint_05_review.md
- docs/metodology/sprints/sprint_06/sprint_06_planning.md
- docs/metodology/sprints/sprint_06/sprint_06_review.md
- docs/metodology/sprints/sprint_07/sprint_07_planning.md
- docs/metodology/sprints/sprint_07/sprint_07_review.md
- docs/metodology/sprints/sprint_08/sprint_08_planning.md
Atualiza documentação das Sprints 06, 07 e 08.
> Sprint documentation

- TropicalHazards_BI/settings.py
- projects/tests.py
- projects/views.py
- users/views.py
Resolve bug nas requisições na view de projeto onde o request.user era retornado como Anonymous User mesmo estando logado.
> Issue 248 fix authentication

- dashboards/admin.py
- dashboards/models.py
- dashboards/views.py
- projects/views.py
- Foram realizadas alterações nas authentication classes da criação de projeto e dashboard e nos métodos post e put de projeto.
> Issue 283 project bug

- .travis.yml
- Dockerfile
- TropicalHazards_BI/settings.py
Configura o deploy e o deploy continuo da aplicação
> Issue 129  continuous deploy

- projects/tests.py
- projects/urls.py
- users/tests.py
- users/urls.py
Co-authored-by: andre <andrebargas@gmail.com>
Co-authored-by: Yoshida <edry97@hotmail.com>
> [FIX] fix urls with incorrect sintax

- import_data/urls.py
- import_data/views.py
- requirements.txt
- [ X ] Adiciona nova funcionalidade  
Adiciona as funcionalidades de visualização dos dados CSV e permite a exclusão de "fields" na base de dados
#268
> Issue 268 Filtrar Import Data

- docs/project_artefacts/usability_test/index.md
- package.json
Adição de detalhamento dos testes e do planejamento dos testes.
> Issue 77 front usability test

- import_data/views.py
- [ X ] Adiciona nova funcionalidade 
Adiciona a funcionalidade de definição do tipo de dado a ser inserido no mongoDB. Requisições são feitas através de parâmetro do método POST do import data
#254
> Issue 254 Definir tipo de dados

- .dockerignore
- docker-compose.yml
- metabase-docker/Dockerfile
- metabase-docker/metabase_setup.py
- metabase-docker/requirements.txt
- metabase-docker/start.sh
Cria Dockerfile configurando super user do Metabase a partir das variáveis de ambiente:
```yml
- MB_FIRST_NAME
- MB_LAST_NAME
- MB_EMAIL
- MB_PASSWORD
```
> Issue 291 Metabase Setup

- .gitignore
- .travis.yml
- README.md
- TropicalHazards_BI/settings.py
- env.tmpl
- nginx/Dockerfile
- nginx/nginx.conf
Define variáveis de ambiente referentes a configuração do django, atualiza pipeline de CD para puxar a imagem para o registry da organização no dockerhub, assim como dar restart no serviço do Nginx. Além disso versiona o Dockerfile do Nginx no repositório.
> Issue 290 environment vars

- TropicalHazards_BI/settings.py
- requirements.txt
Configura sentry para monitorar erros e exceções da aplicação em produção.
> Issue 309 Configure sentry to watch the app

- .gitignore
- boot.sh
Corrige configuração de versionamento das migrações.
> [HOTFIX] fix migrations folders and gitignore config

- docs/metodology/sprints/sprint_07/sprint_07_review.md
- docs/metodology/sprints/sprint_08/sprint_08_review.md
- docs/metodology/sprints/sprint_09/sprint_09_planning.md
- docs/metodology/sprints/sprint_09/sprint_09_review.md
- docs/metodology/sprints/sprint_10/sprint_10_planning.md
- docs/metodology/sprints/sprint_10/sprint_10_review.md
- docs/metodology/sprints/sprint_11/sprint_11_planning.md
> Sprint docs

- .travis.yml
- package.json
> Configures semantic release

- .dockerignore
- .gitignore
- .travis.yml
- semantic-release.sh
- travis-deploy.sh
Corrige processo de CD no travis.
> [HOTFIX] fix travis deploy to rancher

- TropicalHazards_BI/settings.py
- TropicalHazards_BI/urls.py
- metabase-docker/metabase_setup.py
- metabase/admin.py
- metabase/apps.py
- metabase/models.py
- metabase/serializers.py
- metabase/tests.py
- metabase/urls.py
- metabase/utils.py
- metabase/views.py
- requirements.txt
- Resolve as issues 303, 304 e 305
- Trata do fluxo de criar a question no metabase, gerar o iframe e associar ao dashboard
> Issue 303 make question in metabase

- import_data/views.py
- Atualiza o método post para receber uma lista de dicionários
- Atualiza o método post para tratar os dados recebidos conforme especificados nos dicionários
> Issue 300 refact import data post

- package.json
error was no name in the package.json
> [HOTFIX] fixes the automated release error

- docs/metodology/sprints/sprint_10/sprint_10_planning.md
- docs/metodology/sprints/sprint_10/sprint_10_review.md
- docs/metodology/sprints/sprint_11/sprint_11_planning.md
- docs/metodology/sprints/sprint_11/sprint_11_review.md
- docs/metodology/sprints/sprint_12/sprint_12_planning.md
- docs/metodology/sprints/sprint_12/sprint_12_review.md
- docs/metodology/sprints/sprint_13/sprint_13_planning.md
Adiciona documentação das Sprints, atualiza sprint 11 que não foi incluída no merge anterior e pequenas correções.
> Sprint 12 review e Sprint 13 planning

- dashboards/tests.py
- projects/tests.py
- tags/tests.py
- users/tests.py
Refatora testes para utilizar fixtures
> Issue 242 refactoring test

- README.md
- docs/development_docs/doc_visao.md
> Review docs

- README.md
- TropicalHazards_BI/settings.py
> fix(deploy): fix this

- TropicalHazards_BI/utils.py
- import_data/tests.py
- import_data/views.py
- metabase/utils.py
- metabase/views.py
- projects/models.py
- projects/serializers.py
- projects/tests.py
- projects/views.py
Associa collection de um projeto a tabela do metabase equivalente.
> Issue 331 relate project with metabase table

- docs/index.html
- docs/metodology/sprints/sprint_12/sprint_12_planning.md
- docs/metodology/sprints/sprint_13/sprint_13_review.md
- docs/metodology/sprints/sprint_14/sprint_14_planning.md
Minor fixes e documentação das Sprints
> Sprint 13 review and sprint 14 planning

- metabase/urls.py
- metabase/views.py
Co-authored-by: Joao <joaok8@gmail.com>
Co-authored-by: Yoshida<edry97@hotmail.com>
Adiciona novo endpoint na API
#347
> Issue 347 Obtem fields id gerados pelo metabase

- metabase/admin.py
- metabase/models.py
- metabase/utils.py
- metabase/views.py
Adicionando metódo e parâmetro ao end point para definição de parâmetros do iframe
#335
> Issue 335 Definir dimenções de um gráfico

- projects/tests.py
- projects/urls.py
- projects/views.py
Co-authored-by: Joao <joaok8@gmail.com>
Co-authored-by: Yoshida <edry97@hotmail.com>
Cria novo end point para retorno da lista de projetos do usuário logado. Para utilizar nova funcionalidade acessar URL .../projects/user com a requisição HTTP GET.
#350
> Novo end point para retorno de lista de projetos do usuário logado

- docs/index.html
- docs/metodology/sprints/sprint_13/sprint_13_review.md
- docs/metodology/sprints/sprint_14/sprint_14_review.md
- docs/metodology/sprints/sprint_15/sprint_15_planning.md
> [DOC] Adding Sprint 14 Review and Sprint 15 planning

- metabase/views.py
Co-authored-by: Yoshida <edry97@hotmail.com>
Método do end-point atualizado, podendo agora receber parâmetros para a definição da query utilizada na criação dos iframes. Os novo parâmetro do payload são :
**query_filter** : (filter da query padrão do metabase)
**query_aggregation** (aggregation do metabase, onde define como dados serão agrupados)
**query_breakout** (breakout do metabase, onde os dados podem ser delimitados)
Estes parâmetros foram incorporados aos já existentes.
#354
> Filtro para criação de Iframe

- metabase/utils.py
Valida token do metabase antes de retorná-lo para ser usado nas requisições, caso o token tenha expirado ele é recriado.
> Validate metabase auth token

- TropicalHazards_BI/settings.py
- Permite logout pelo método http get, resolvendo bug com csrf token.
> [UPDATE] changes to logout method

- metabase/views.py
- Corrige bug ao receber as visualization settings
> [FIX] fixed visualization settings
